<!-- This stylesheet converts the HTML generated by Beacon back to GuideXML -->
<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"> 

<xsl:output method="xml" encoding="UTF-8" indent="yes"/>

<xsl:template match="div[@id='guide']">
    <guide link="{@link}">
	<title><xsl:value-of select="div[@id='mainContent']/div[@class='title']/h1"/></title>
	<xsl:for-each select="div[@id='sideContent']/div[@class='authors']/div">
	    <author title="{i[@dojoType='inlineEditBox']}">
		<xsl:choose>
		    <xsl:when test="a[@href]">
			<xsl:for-each select="a">
			    <mail link="{@href}"><xsl:value-of select="."/></mail>
			</xsl:for-each>
		    </xsl:when>
		    <xsl:otherwise>
			<xsl:value-of select="a"/>
		    </xsl:otherwise>
		</xsl:choose>
	    </author>
	</xsl:for-each>
	<abstract><xsl:value-of select="div[@class='abstract']/p"/></abstract>
	<license/>
	<!-- Extract hidden version ;) -->
	<version><xsl:value-of select="div[@class='version']"/></version>
	<date><xsl:value-of select="div[@class='date']/div"/></date>
	<xsl:for-each select="div[@id='mainContent']/div[@class='chapter']">
	    <chapter>
		<title><xsl:value-of select="h2"/></title>
		<xsl:for-each select="div[@class='section']">
		    <section>
			<title><xsl:value-of select="h3"/></title>
			<body>
			    <xsl:for-each select="div">
				<xsl:choose>
				    <!-- <pre> was treated specially, so it must be the same here too! -->
				    <xsl:when test="@class='code'">
					<xsl:copy-of select="div[@mode='textarea']/pre"/>	
				    </xsl:when>
				    <!-- We can afford to use <otherwise> here :) -->
				    <xsl:otherwise>
					<xsl:copy-of select="child::*"/>
				    </xsl:otherwise>
				</xsl:choose>
			    </xsl:for-each>
			</body>
		    </section>
		</xsl:for-each>
	    </chapter>
	</xsl:for-each>
    </guide>
</xsl:template>

</xsl:stylesheet>
<!-- There ye go! -->