<?php

$pages = array(
    "miscellaneous" => array(
        "File was deleted successfully" =>
            "File was deleted successfully",

        "File could not be deleted" =>
            "File could not be deleted",
    ),

    "beaconfull.html" => array(
        "Beacon" =>
            "Beacon"
    ),

    "beaconui.html" => array(
        "Welcome" =>
            "Welcome",

        "Create a New Document" =>
            "Create a New Document",

        "File Name:" =>
            "File Name:",

        "Choose Document Type:" =>
            "Choose Document Type:",

        "Select one" =>
            "Select one",

        "Create New!" =>
            "Create New!",

        "Edit a Document" =>
            "Edit a Document",

        "Choose where to fetch the document from:" =>
            "Choose where to fetch the document from:",

        "Upload a file" =>
            "Upload a file",

        "From URL" =>
            "From URL",

        "Go Edit!" =>
            "Go Edit!",

        "Welcome to Beacon. A WYSIWYG (and much more!) Editor." =>
            "Welcome to Beacon. A WYSIWYG (and much more!) Editor.",

        "Choose an action from the menu on the right." =>
            "Choose an action from the menu on the right.",

        "1. Create a New Document:" =>
            "1. Create a New Document:",

        "Create a new document using the plugin's template for new documents." =>
            "Create a new document using the plugin's template for new documents.",

        "2. Edit a document:" =>
            "2. Edit a document:",

        "You can either fetch an existing document at a give URL or upload a file depending on the plugin." =>
            "You can either fetch an existing document at a give URL or upload a file depending on the plugin.",

        "To close a tab click the top right icon having a cross." =>
            "To close a tab click the top right icon having a cross.",

        "Access live help by clicking the ? button which opens a tab with IRC chat in #beacon on Freenode." =>
            "Access live help by clicking the ? button which opens a tab with IRC chat in #beacon on Freenode.",

        "Homepage:" =>
            "Homepage:",

        "Status:" =>
            "Status:",

        "Configuration" =>
            "Configuration",

        "Plugins Loaded:" =>
            "Plugins Loaded:",

        "Language:" =>
            "Language:",

        "Theme:" =>
            "Theme:"
    ),

    "document.html" => array(
        "Save" =>
            "Save",

        "View Source" =>
            "View Source",

        "Download" =>
            "Download"
    )
);

return $pages;

?>