<?php

$pages = array(
    "miscellaneous" => array(
        "File was deleted successfully" =>
            "File was deleted successfully",

        "File could not be deleted" =>
            "File could not be deleted",
    ),

    "beaconfull.html" => array(
        "Beacon" =>
            "Beacon"
    ),

    "beaconui.html" => array(
        "Welcome" =>
            "Welcome",

        "Your Documents" =>
            "Your Documents",

        "Create a New Document" =>
            "Create a New Document",

        "File Name:" =>
            "File Name:",

        "Choose Document Type:" =>
            "Choose Document Type:",

        "Select one" =>
            "Select one",

        "Create New!" =>
            "Create New!",

        "Edit a Remote Document" =>
            "Edit a Remote Document",

        "Select a file:" =>
            "Select a file:",

        "Enter a URL to fetch from:" =>
            "Enter a URL to fetch from:",

        "Fetch" =>
            "Fetch",

        "Welcome to Beacon. A WYSIWYG (and much more!) Editor." =>
            "Welcome to Beacon. A WYSIWYG (and much more!) Editor.",

        "Choose an action from the menu on the right." =>
            "Choose an action from the menu on the right.",

        "1. Create a New Document:" =>
            "1. Create a New Document:",

        "Create a new document using the plugin's template for new documents." =>
            "Create a new document using the plugin's template for new documents.",

        "2. Edit a document:" =>
            "2. Edit a document:",

        "You can either fetch an existing document at a give URL or upload a file depending on the plugin." =>
            "You can either fetch an existing document at a give URL or upload a file depending on the plugin.",

        "To close a tab click the top right icon having a cross." =>
            "To close a tab click the top right icon having a cross.",

        "Access live help by clicking the ? button which opens a tab with IRC chat in #beacon on Freenode." =>
            "Access live help by clicking the ? button which opens a tab with IRC chat in #beacon on Freenode.",

        "Homepage:" =>
            "Homepage:",

        "Status:" =>
            "Status:",

        "Configuration" =>
            "Configuration",

        "Plugins Loaded:" =>
            "Plugins Loaded:",

        "Language:" =>
            "Language:",

        "Theme:" =>
            "Theme:",

        "Loading..." =>
            "Loading..."
    ),

    "document.html" => array(
        "Save the document" =>
            "Save the document",

        "Show/Hide Source View" =>
            "Show/Hide Source View",

        "Delete the node" =>
            "Delete the node",

        "Insert Block Element" =>
            "Insert Block Element",

        "Insert around a Node:" =>
            "Insert around a Node:",

        "Before" =>
            "Before",

        "After" =>
            "After",

        "Select Any One" =>
            "Select Any One",

        "Insert Block Element" =>
            "Insert Block Element",

        "Insert around a Node:" =>
            "Insert around a Node:",

        "Insert Inline Element" =>
            "Insert Inline Element",

        "Document Tree" =>
            "Document Tree",

        "Last saved:" =>
            "Last saved:",

        "Please wait. Loading..." =>
            "Please wait. Loading...",

        "Select type:" =>
            "Select type:",

        "Highlight some text while editing rich text type nodes," =>
            "Highlight some text while editing rich text type nodes,",

        "and then choose a type of inline element and click" =>
            "and then choose a type of inline element and click",

        "This will highlight the selected text as that inline element style." =>
            "This will highlight the selected text as that inline element style.",

        "Loading..." =>
            "Loading...",
    )
);

return $pages;

?>